allowBuilds:
  esbuild: true
  lightningcss: true
onlyBuiltDependencies:
  - esbuild
  - lightningcss
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
minimumReleaseAgeExclude:
  - electron-to-chromium
  - baseline-browser-mapping
