/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BotCodeRouteImport } from './routes/bot.$code'
import { Route as ChannelChannelIdRouteImport } from './routes/channel.$channelId'
import { Route as DiscoverSplatRouteImport } from './routes/discover.$'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginAuthRouteImport } from './routes/login/auth'
import { Route as LoginCheckRouteImport } from './routes/login/check'
import { Route as LoginCreateRouteImport } from './routes/login/create'
import { Route as LoginResendRouteImport } from './routes/login/resend'
import { Route as LoginResetRouteImport } from './routes/login/reset'
import { Route as ServerServerIdRouteImport } from './routes/server.$serverId'
import { Route as ChannelChannelIdIndexRouteImport } from './routes/channel.$channelId.index'
import { Route as ChannelChannelIdMessageIdRouteImport } from './routes/channel.$channelId.$messageId'
import { Route as LoginCreateIndexRouteImport } from './routes/login/create.index'
import { Route as LoginCreateCodeRouteImport } from './routes/login/create.$code'
import { Route as LoginDeleteTokenRouteImport } from './routes/login/delete.$token'
import { Route as LoginResetIndexRouteImport } from './routes/login/reset.index'
import { Route as LoginResetTokenRouteImport } from './routes/login/reset.$token'
import { Route as LoginVerifyTokenRouteImport } from './routes/login/verify.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BotCodeRoute = BotCodeRouteImport.update({
  id: '/bot/$code',
  path: '/bot/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdRoute = ChannelChannelIdRouteImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverSplatRoute = DiscoverSplatRouteImport.update({
  id: '/discover/$',
  path: '/discover/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAuthRoute = LoginAuthRouteImport.update({
  id: '/login/auth',
  path: '/login/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCheckRoute = LoginCheckRouteImport.update({
  id: '/login/check',
  path: '/login/check',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCreateRoute = LoginCreateRouteImport.update({
  id: '/login/create',
  path: '/login/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginResendRoute = LoginResendRouteImport.update({
  id: '/login/resend',
  path: '/login/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginResetRoute = LoginResetRouteImport.update({
  id: '/login/reset',
  path: '/login/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerServerIdRoute = ServerServerIdRouteImport.update({
  id: '/server/$serverId',
  path: '/server/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdIndexRoute = ChannelChannelIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChannelChannelIdRoute,
} as any)
const ChannelChannelIdMessageIdRoute =
  ChannelChannelIdMessageIdRouteImport.update({
    id: '/$messageId',
    path: '/$messageId',
    getParentRoute: () => ChannelChannelIdRoute,
  } as any)
const LoginCreateIndexRoute = LoginCreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginCreateRoute,
} as any)
const LoginCreateCodeRoute = LoginCreateCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => LoginCreateRoute,
} as any)
const LoginDeleteTokenRoute = LoginDeleteTokenRouteImport.update({
  id: '/login/delete/$token',
  path: '/login/delete/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginResetIndexRoute = LoginResetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginResetRoute,
} as any)
const LoginResetTokenRoute = LoginResetTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => LoginResetRoute,
} as any)
const LoginVerifyTokenRoute = LoginVerifyTokenRouteImport.update({
  id: '/login/verify/$token',
  path: '/login/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/friends': typeof FriendsRoute
  '/settings': typeof SettingsRoute
  '/bot/$code': typeof BotCodeRoute
  '/channel/$channelId': typeof ChannelChannelIdRouteWithChildren
  '/discover/$': typeof DiscoverSplatRoute
  '/invite/$code': typeof InviteCodeRoute
  '/login/auth': typeof LoginAuthRoute
  '/login/check': typeof LoginCheckRoute
  '/login/create': typeof LoginCreateRouteWithChildren
  '/login/resend': typeof LoginResendRoute
  '/login/reset': typeof LoginResetRouteWithChildren
  '/server/$serverId': typeof ServerServerIdRoute
  '/login/': typeof LoginIndexRoute
  '/channel/$channelId/$messageId': typeof ChannelChannelIdMessageIdRoute
  '/login/create/$code': typeof LoginCreateCodeRoute
  '/login/delete/$token': typeof LoginDeleteTokenRoute
  '/login/reset/$token': typeof LoginResetTokenRoute
  '/login/verify/$token': typeof LoginVerifyTokenRoute
  '/channel/$channelId/': typeof ChannelChannelIdIndexRoute
  '/login/create/': typeof LoginCreateIndexRoute
  '/login/reset/': typeof LoginResetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/friends': typeof FriendsRoute
  '/settings': typeof SettingsRoute
  '/bot/$code': typeof BotCodeRoute
  '/discover/$': typeof DiscoverSplatRoute
  '/invite/$code': typeof InviteCodeRoute
  '/login/auth': typeof LoginAuthRoute
  '/login/check': typeof LoginCheckRoute
  '/login/resend': typeof LoginResendRoute
  '/server/$serverId': typeof ServerServerIdRoute
  '/login': typeof LoginIndexRoute
  '/channel/$channelId/$messageId': typeof ChannelChannelIdMessageIdRoute
  '/login/create/$code': typeof LoginCreateCodeRoute
  '/login/delete/$token': typeof LoginDeleteTokenRoute
  '/login/reset/$token': typeof LoginResetTokenRoute
  '/login/verify/$token': typeof LoginVerifyTokenRoute
  '/channel/$channelId': typeof ChannelChannelIdIndexRoute
  '/login/create': typeof LoginCreateIndexRoute
  '/login/reset': typeof LoginResetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/friends': typeof FriendsRoute
  '/settings': typeof SettingsRoute
  '/bot/$code': typeof BotCodeRoute
  '/channel/$channelId': typeof ChannelChannelIdRouteWithChildren
  '/discover/$': typeof DiscoverSplatRoute
  '/invite/$code': typeof InviteCodeRoute
  '/login/auth': typeof LoginAuthRoute
  '/login/check': typeof LoginCheckRoute
  '/login/create': typeof LoginCreateRouteWithChildren
  '/login/resend': typeof LoginResendRoute
  '/login/reset': typeof LoginResetRouteWithChildren
  '/server/$serverId': typeof ServerServerIdRoute
  '/login/': typeof LoginIndexRoute
  '/channel/$channelId/$messageId': typeof ChannelChannelIdMessageIdRoute
  '/login/create/$code': typeof LoginCreateCodeRoute
  '/login/delete/$token': typeof LoginDeleteTokenRoute
  '/login/reset/$token': typeof LoginResetTokenRoute
  '/login/verify/$token': typeof LoginVerifyTokenRoute
  '/channel/$channelId/': typeof ChannelChannelIdIndexRoute
  '/login/create/': typeof LoginCreateIndexRoute
  '/login/reset/': typeof LoginResetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/friends'
    | '/settings'
    | '/bot/$code'
    | '/channel/$channelId'
    | '/discover/$'
    | '/invite/$code'
    | '/login/auth'
    | '/login/check'
    | '/login/create'
    | '/login/resend'
    | '/login/reset'
    | '/server/$serverId'
    | '/login/'
    | '/channel/$channelId/$messageId'
    | '/login/create/$code'
    | '/login/delete/$token'
    | '/login/reset/$token'
    | '/login/verify/$token'
    | '/channel/$channelId/'
    | '/login/create/'
    | '/login/reset/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/friends'
    | '/settings'
    | '/bot/$code'
    | '/discover/$'
    | '/invite/$code'
    | '/login/auth'
    | '/login/check'
    | '/login/resend'
    | '/server/$serverId'
    | '/login'
    | '/channel/$channelId/$messageId'
    | '/login/create/$code'
    | '/login/delete/$token'
    | '/login/reset/$token'
    | '/login/verify/$token'
    | '/channel/$channelId'
    | '/login/create'
    | '/login/reset'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/friends'
    | '/settings'
    | '/bot/$code'
    | '/channel/$channelId'
    | '/discover/$'
    | '/invite/$code'
    | '/login/auth'
    | '/login/check'
    | '/login/create'
    | '/login/resend'
    | '/login/reset'
    | '/server/$serverId'
    | '/login/'
    | '/channel/$channelId/$messageId'
    | '/login/create/$code'
    | '/login/delete/$token'
    | '/login/reset/$token'
    | '/login/verify/$token'
    | '/channel/$channelId/'
    | '/login/create/'
    | '/login/reset/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  FriendsRoute: typeof FriendsRoute
  SettingsRoute: typeof SettingsRoute
  BotCodeRoute: typeof BotCodeRoute
  ChannelChannelIdRoute: typeof ChannelChannelIdRouteWithChildren
  DiscoverSplatRoute: typeof DiscoverSplatRoute
  InviteCodeRoute: typeof InviteCodeRoute
  LoginAuthRoute: typeof LoginAuthRoute
  LoginCheckRoute: typeof LoginCheckRoute
  LoginCreateRoute: typeof LoginCreateRouteWithChildren
  LoginResendRoute: typeof LoginResendRoute
  LoginResetRoute: typeof LoginResetRouteWithChildren
  ServerServerIdRoute: typeof ServerServerIdRoute
  LoginIndexRoute: typeof LoginIndexRoute
  LoginDeleteTokenRoute: typeof LoginDeleteTokenRoute
  LoginVerifyTokenRoute: typeof LoginVerifyTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot/$code': {
      id: '/bot/$code'
      path: '/bot/$code'
      fullPath: '/bot/$code'
      preLoaderRoute: typeof BotCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId': {
      id: '/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof ChannelChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/$': {
      id: '/discover/$'
      path: '/discover/$'
      fullPath: '/discover/$'
      preLoaderRoute: typeof DiscoverSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/auth': {
      id: '/login/auth'
      path: '/login/auth'
      fullPath: '/login/auth'
      preLoaderRoute: typeof LoginAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/check': {
      id: '/login/check'
      path: '/login/check'
      fullPath: '/login/check'
      preLoaderRoute: typeof LoginCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/create': {
      id: '/login/create'
      path: '/login/create'
      fullPath: '/login/create'
      preLoaderRoute: typeof LoginCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/resend': {
      id: '/login/resend'
      path: '/login/resend'
      fullPath: '/login/resend'
      preLoaderRoute: typeof LoginResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/reset': {
      id: '/login/reset'
      path: '/login/reset'
      fullPath: '/login/reset'
      preLoaderRoute: typeof LoginResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/$serverId': {
      id: '/server/$serverId'
      path: '/server/$serverId'
      fullPath: '/server/$serverId'
      preLoaderRoute: typeof ServerServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId/': {
      id: '/channel/$channelId/'
      path: '/'
      fullPath: '/channel/$channelId/'
      preLoaderRoute: typeof ChannelChannelIdIndexRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/$messageId': {
      id: '/channel/$channelId/$messageId'
      path: '/$messageId'
      fullPath: '/channel/$channelId/$messageId'
      preLoaderRoute: typeof ChannelChannelIdMessageIdRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/login/create/': {
      id: '/login/create/'
      path: '/'
      fullPath: '/login/create/'
      preLoaderRoute: typeof LoginCreateIndexRouteImport
      parentRoute: typeof LoginCreateRoute
    }
    '/login/create/$code': {
      id: '/login/create/$code'
      path: '/$code'
      fullPath: '/login/create/$code'
      preLoaderRoute: typeof LoginCreateCodeRouteImport
      parentRoute: typeof LoginCreateRoute
    }
    '/login/delete/$token': {
      id: '/login/delete/$token'
      path: '/login/delete/$token'
      fullPath: '/login/delete/$token'
      preLoaderRoute: typeof LoginDeleteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/reset/': {
      id: '/login/reset/'
      path: '/'
      fullPath: '/login/reset/'
      preLoaderRoute: typeof LoginResetIndexRouteImport
      parentRoute: typeof LoginResetRoute
    }
    '/login/reset/$token': {
      id: '/login/reset/$token'
      path: '/$token'
      fullPath: '/login/reset/$token'
      preLoaderRoute: typeof LoginResetTokenRouteImport
      parentRoute: typeof LoginResetRoute
    }
    '/login/verify/$token': {
      id: '/login/verify/$token'
      path: '/login/verify/$token'
      fullPath: '/login/verify/$token'
      preLoaderRoute: typeof LoginVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChannelChannelIdRouteChildren {
  ChannelChannelIdMessageIdRoute: typeof ChannelChannelIdMessageIdRoute
  ChannelChannelIdIndexRoute: typeof ChannelChannelIdIndexRoute
}

const ChannelChannelIdRouteChildren: ChannelChannelIdRouteChildren = {
  ChannelChannelIdMessageIdRoute: ChannelChannelIdMessageIdRoute,
  ChannelChannelIdIndexRoute: ChannelChannelIdIndexRoute,
}

const ChannelChannelIdRouteWithChildren =
  ChannelChannelIdRoute._addFileChildren(ChannelChannelIdRouteChildren)

interface LoginCreateRouteChildren {
  LoginCreateCodeRoute: typeof LoginCreateCodeRoute
  LoginCreateIndexRoute: typeof LoginCreateIndexRoute
}

const LoginCreateRouteChildren: LoginCreateRouteChildren = {
  LoginCreateCodeRoute: LoginCreateCodeRoute,
  LoginCreateIndexRoute: LoginCreateIndexRoute,
}

const LoginCreateRouteWithChildren = LoginCreateRoute._addFileChildren(
  LoginCreateRouteChildren,
)

interface LoginResetRouteChildren {
  LoginResetTokenRoute: typeof LoginResetTokenRoute
  LoginResetIndexRoute: typeof LoginResetIndexRoute
}

const LoginResetRouteChildren: LoginResetRouteChildren = {
  LoginResetTokenRoute: LoginResetTokenRoute,
  LoginResetIndexRoute: LoginResetIndexRoute,
}

const LoginResetRouteWithChildren = LoginResetRoute._addFileChildren(
  LoginResetRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  FriendsRoute: FriendsRoute,
  SettingsRoute: SettingsRoute,
  BotCodeRoute: BotCodeRoute,
  ChannelChannelIdRoute: ChannelChannelIdRouteWithChildren,
  DiscoverSplatRoute: DiscoverSplatRoute,
  InviteCodeRoute: InviteCodeRoute,
  LoginAuthRoute: LoginAuthRoute,
  LoginCheckRoute: LoginCheckRoute,
  LoginCreateRoute: LoginCreateRouteWithChildren,
  LoginResendRoute: LoginResendRoute,
  LoginResetRoute: LoginResetRouteWithChildren,
  ServerServerIdRoute: ServerServerIdRoute,
  LoginIndexRoute: LoginIndexRoute,
  LoginDeleteTokenRoute: LoginDeleteTokenRoute,
  LoginVerifyTokenRoute: LoginVerifyTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
